// ============================================
//      Prince Md — COMMANDS/AIIMAGE.JS
//      AI Image Generation
// ============================================

'use strict';

const axios = require('axios');
const { toSmallCaps } = require('../utils/fonts');

// ─── .aiimage ────────────────────────────────────────────
const aiimage = async (ctx) => {
  const { sock, msg, from, sender, args } = ctx;

  const prompt = args.join(' ');
  if (!prompt) {
    return ctx.reply(`❌ *${toSmallCaps('provide an image description')}*\n\n*Example:* .aiimage A beautiful sunset over mountains`);
  }

  await ctx.reply(`🎨 *${toSmallCaps('generating AI image')}* "${prompt}"...`);

  try {
    // Using DALL-E API (you'll need to add your API key)
    const response = await axios.post('https://api.openai.com/v1/images/generations', {
      prompt: prompt,
      n: 1,
      size: '1024x1024',
      response_format: 'url'
    }, {
      headers: {
        'Authorization': 'Bearer YOUR_OPENAI_API_KEY', // Replace with your API key
        'Content-Type': 'application/json'
      }
    });

    const imageUrl = response.data.data[0].url;

    await ctx.reply(`🎨 *${toSmallCaps('AI image generated successfully')}*`);

    // Send the generated image
    await sock.sendMessage(from, {
      image: { url: imageUrl },
      caption: `🎨 *${toSmallCaps('AI Generated Image')}*\n\n📝 *${toSmallCaps('prompt')}:* ${prompt}\n🤖 *${toSmallCaps('generated by')}:* DALL-E\n📱 *${toSmallCaps('bot')}:* Prince Md\n\n> ${toSmallCaps('powered by OpenAI')}`
    }, { quoted: msg });

  } catch (error) {
    console.log('[AIIMAGE ERROR]', error.message);
    
    // Fallback: Send a placeholder image
    await ctx.reply(`❌ *${toSmallCaps('image generation failed')}*\n\n${toSmallCaps('please check API key and try again')}`);
    
    // Send a placeholder image
    try {
      await sock.sendMessage(from, {
        image: { url: 'https://picsum.photos/1024/1024?random=' + Math.random() },
        caption: `🎨 *${toSmallCaps('placeholder image')}*\n\n📝 *${toSmallCaps('prompt')}:* ${prompt}\n⚠️ *${toSmallCaps('AI generation unavailable')}\n\n> ${toSmallCaps('showing random image instead')}`
      }, { quoted: msg });
    } catch (err) {
      console.log('Placeholder image error:', err.message);
    }
  }
};

module.exports = { aiimage };
