'use strict';

const { toSmallCaps } = require('../utils/fonts');

const aiimage = async (ctx) => {
  const { sock, msg, from, args } = ctx;
  const prompt = args.join(' ').trim();

  if (!prompt) {
    return ctx.reply(`❌ *${toSmallCaps('provide an image description')}*\n\n*Example:* .aiimage A beautiful sunset over mountains`);
  }

  await ctx.reply(`🎨 *${toSmallCaps('generating ai image')}* "${prompt}"...`);

  try {
    const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&nologo=true&enhance=true&seed=${Date.now()}`;

    await sock.sendMessage(from, {
      image: { url: imageUrl },
      caption: `🎨 *${toSmallCaps('ai generated image')}*\n\n📝 *${toSmallCaps('prompt')}:* ${prompt}\n🤖 *${toSmallCaps('generated by')}:* AI Image API\n📱 *${toSmallCaps('bot')}:* Prince Md`,
    }, { quoted: msg });
  } catch (error) {
    console.log('[AIIMAGE ERROR]', error.message);
    await ctx.reply(`❌ *${toSmallCaps('image generation failed')}*\n\n${toSmallCaps('please try again')}`);
  }
};

module.exports = { aiimage };
